version: "3.9"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
      POSTGRES_DB: module_7
    volumes:
      - pgdata:/ver/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  pgdata: