"""Init

Revision ID: b1af385455ca
Create Date: 2025-05-10 00:08:07.543724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1af385455ca'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=175), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('grade_date', sa.Date(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('teachers_to_students')
    op.add_column('students', sa.Column('fullname', sa.String(length=150), nullable=False))
    op.add_column('students', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'students', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.drop_column('students', 'email')
    op.drop_column('students', 'address')
    op.drop_column('students', 'first_name')
    op.drop_column('students', 'cell_phone')
    op.drop_column('students', 'last_name')
    op.add_column('teachers', sa.Column('fullname', sa.String(length=150), nullable=False))
    op.drop_column('teachers', 'email')
    op.drop_column('teachers', 'start_work')
    op.drop_column('teachers', 'address')
    op.drop_column('teachers', 'first_name')
    op.drop_column('teachers', 'cell_phone')
    op.drop_column('teachers', 'last_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('last_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('teachers', sa.Column('cell_phone', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('teachers', sa.Column('first_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('teachers', sa.Column('address', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('teachers', sa.Column('start_work', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('teachers', sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('teachers', 'fullname')
    op.add_column('students', sa.Column('last_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('cell_phone', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('first_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('address', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_column('students', 'group_id')
    op.drop_column('students', 'fullname')
    op.create_table('teachers_to_students',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name='teachers_to_students_student_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], name='teachers_to_students_teacher_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='teachers_to_students_pkey')
    )
    op.drop_table('grades')
    op.drop_table('subjects')
    op.drop_table('groups')
    # ### end Alembic commands ###
